// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/goods.proto

package typeTemplate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//--response
//response.rows;//结果
//respons
//--requeste.total;//更新总记录数
//
//seller/search.do?page=1&rows=10
//{status: "0"}
type ReqSearch struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSearch) Reset()         { *m = ReqSearch{} }
func (m *ReqSearch) String() string { return proto.CompactTextString(m) }
func (*ReqSearch) ProtoMessage()    {}
func (*ReqSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{0}
}

func (m *ReqSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSearch.Unmarshal(m, b)
}
func (m *ReqSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSearch.Marshal(b, m, deterministic)
}
func (m *ReqSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSearch.Merge(m, src)
}
func (m *ReqSearch) XXX_Size() int {
	return xxx_messageInfo_ReqSearch.Size(m)
}
func (m *ReqSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSearch proto.InternalMessageInfo

func (m *ReqSearch) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqSearch) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type ReqIds struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIds) Reset()         { *m = ReqIds{} }
func (m *ReqIds) String() string { return proto.CompactTextString(m) }
func (*ReqIds) ProtoMessage()    {}
func (*ReqIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{1}
}

func (m *ReqIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIds.Unmarshal(m, b)
}
func (m *ReqIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIds.Marshal(b, m, deterministic)
}
func (m *ReqIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIds.Merge(m, src)
}
func (m *ReqIds) XXX_Size() int {
	return xxx_messageInfo_ReqIds.Size(m)
}
func (m *ReqIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIds.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIds proto.InternalMessageInfo

func (m *ReqIds) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

//{total:100,rows:[{id:1,name:234,firstChar:N,firstName:2}]}
type RespSearch struct {
	Total                int64    `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*Rows  `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSearch) Reset()         { *m = RespSearch{} }
func (m *RespSearch) String() string { return proto.CompactTextString(m) }
func (*RespSearch) ProtoMessage()    {}
func (*RespSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{2}
}

func (m *RespSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSearch.Unmarshal(m, b)
}
func (m *RespSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSearch.Marshal(b, m, deterministic)
}
func (m *RespSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSearch.Merge(m, src)
}
func (m *RespSearch) XXX_Size() int {
	return xxx_messageInfo_RespSearch.Size(m)
}
func (m *RespSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RespSearch proto.InternalMessageInfo

func (m *RespSearch) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespSearch) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

//{"customAttributeItems":[{"text":"1"},{"text":"1"}],"name":"1","brandIds":[{"id":2,"text":"华为"}],"specIds":[{"id":33,"text":"电视屏幕尺寸1"}]}
type Rows struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SpecIds              string   `protobuf:"bytes,3,opt,name=specIds,proto3" json:"specIds,omitempty"`
	BrandIds             string   `protobuf:"bytes,4,opt,name=brandIds,proto3" json:"brandIds,omitempty"`
	CustomAttributeItems string   `protobuf:"bytes,5,opt,name=customAttributeItems,proto3" json:"customAttributeItems,omitempty"`
	SspecIds             string   `protobuf:"bytes,6,opt,name=sspecIds,proto3" json:"sspecIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{3}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rows) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rows) GetSpecIds() string {
	if m != nil {
		return m.SpecIds
	}
	return ""
}

func (m *Rows) GetBrandIds() string {
	if m != nil {
		return m.BrandIds
	}
	return ""
}

func (m *Rows) GetCustomAttributeItems() string {
	if m != nil {
		return m.CustomAttributeItems
	}
	return ""
}

func (m *Rows) GetSspecIds() string {
	if m != nil {
		return m.SspecIds
	}
	return ""
}

type Models struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Models) Reset()         { *m = Models{} }
func (m *Models) String() string { return proto.CompactTextString(m) }
func (*Models) ProtoMessage()    {}
func (*Models) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{4}
}

func (m *Models) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Models.Unmarshal(m, b)
}
func (m *Models) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Models.Marshal(b, m, deterministic)
}
func (m *Models) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Models.Merge(m, src)
}
func (m *Models) XXX_Size() int {
	return xxx_messageInfo_Models.Size(m)
}
func (m *Models) XXX_DiscardUnknown() {
	xxx_messageInfo_Models.DiscardUnknown(m)
}

var xxx_messageInfo_Models proto.InternalMessageInfo

func (m *Models) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Models) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaeb1a212db58e32, []int{5}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSearch)(nil), "ReqSearch")
	proto.RegisterType((*ReqIds)(nil), "ReqIds")
	proto.RegisterType((*RespSearch)(nil), "RespSearch")
	proto.RegisterType((*Rows)(nil), "Rows")
	proto.RegisterType((*Models)(nil), "Models")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/goods.proto", fileDescriptor_eaeb1a212db58e32) }

var fileDescriptor_eaeb1a212db58e32 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5d, 0x6b, 0xea, 0x40,
	0x10, 0x35, 0xe6, 0x43, 0x1d, 0x2f, 0x97, 0xcb, 0xe0, 0x85, 0x98, 0x87, 0x8b, 0xe4, 0xbe, 0xf8,
	0x50, 0x22, 0x68, 0x5f, 0xfb, 0x20, 0x94, 0x82, 0x0f, 0xa5, 0xb0, 0xb5, 0x3f, 0x60, 0x75, 0xa7,
	0x36, 0x90, 0x8f, 0x35, 0xbb, 0x62, 0xfb, 0x5b, 0xfa, 0x27, 0xfa, 0x13, 0xcb, 0x6e, 0x12, 0x95,
	0xe2, 0xdb, 0x39, 0x73, 0x76, 0xce, 0x4c, 0xe6, 0x04, 0xfe, 0xc9, 0xaa, 0xd4, 0xe5, 0x8c, 0x57,
	0xc4, 0xd5, 0x4c, 0x7f, 0x48, 0x5a, 0x53, 0x2e, 0x33, 0xae, 0x29, 0xb1, 0x42, 0xbc, 0x80, 0x01,
	0xa3, 0xfd, 0x33, 0xf1, 0x6a, 0xfb, 0x86, 0x08, 0x9e, 0xe4, 0x3b, 0x0a, 0x9d, 0x89, 0x33, 0xf5,
	0x99, 0xc5, 0xa6, 0x56, 0x95, 0x47, 0x15, 0x76, 0xeb, 0x9a, 0xc1, 0x71, 0x04, 0x01, 0xa3, 0xfd,
	0x4a, 0x28, 0xfc, 0x03, 0x6e, 0x2a, 0x54, 0xe8, 0x4c, 0xdc, 0xe9, 0x80, 0x19, 0x18, 0xdf, 0x01,
	0x30, 0x52, 0xb2, 0x71, 0x1c, 0x81, 0xaf, 0x4b, 0xcd, 0x33, 0x6b, 0x89, 0xac, 0x26, 0x38, 0x3e,
	0x79, 0xba, 0xd3, 0xe1, 0xdc, 0x4f, 0x58, 0x79, 0x54, 0x8d, 0xf5, 0x97, 0x03, 0x9e, 0xa1, 0xf8,
	0x1b, 0xba, 0xa9, 0x68, 0xda, 0xba, 0xa9, 0x30, 0x7b, 0x14, 0x3c, 0x27, 0xbb, 0xc7, 0x80, 0x59,
	0x8c, 0x21, 0xf4, 0x94, 0xa4, 0xed, 0x4a, 0xa8, 0xd0, 0xb5, 0xe5, 0x96, 0x62, 0x04, 0xfd, 0x4d,
	0xc5, 0x0b, 0x61, 0x24, 0xcf, 0x4a, 0x27, 0x8e, 0x73, 0x18, 0x6d, 0x0f, 0x4a, 0x97, 0xf9, 0x52,
	0xeb, 0x2a, 0xdd, 0x1c, 0x34, 0xad, 0x34, 0xe5, 0x2a, 0xf4, 0xed, 0xbb, 0xab, 0x9a, 0xf1, 0x53,
	0xed, 0xa8, 0xa0, 0xf6, 0x6b, 0x79, 0x7c, 0x03, 0xc1, 0x63, 0x29, 0x28, 0xbb, 0xba, 0xb3, 0xa6,
	0x77, 0xdd, 0xee, 0x6c, 0x70, 0x7c, 0x0b, 0x9e, 0xb9, 0x8f, 0xd1, 0x5e, 0x33, 0xbe, 0xb3, 0xaf,
	0xfb, 0xcc, 0x62, 0xf3, 0x3d, 0x39, 0x29, 0x65, 0x22, 0xa8, 0x5b, 0x5a, 0x3a, 0xff, 0x74, 0xe0,
	0xd7, 0xfa, 0x22, 0x3d, 0xfc, 0x0f, 0x41, 0x73, 0x62, 0x48, 0x4e, 0x01, 0x46, 0xc3, 0xe4, 0x7c,
	0xfb, 0xb8, 0x83, 0x7f, 0xc1, 0x5d, 0x0a, 0x81, 0xf5, 0x81, 0x23, 0xdf, 0x8a, 0x71, 0x07, 0x23,
	0x08, 0xee, 0x29, 0x23, 0x4d, 0xd8, 0x4b, 0xea, 0x1c, 0xcf, 0xda, 0x18, 0x7a, 0x0f, 0x69, 0x21,
	0x9e, 0x0a, 0xba, 0x68, 0x33, 0xc1, 0x74, 0x30, 0x84, 0xe0, 0x45, 0x0a, 0x33, 0xfc, 0x87, 0xe1,
	0x26, 0xb0, 0xff, 0xd2, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x27, 0x24, 0x7d, 0x28, 0x6d, 0x02,
	0x00, 0x00,
}
