// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/brand.proto

package brand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//--response
//response.rows;//结果
//respons
//--requeste.total;//更新总记录数
//
//seller/search.do?page=1&rows=10
//{status: "0"}
type ReqBrand struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FirstChar            string   `protobuf:"bytes,4,opt,name=firstChar,proto3" json:"firstChar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBrand) Reset()         { *m = ReqBrand{} }
func (m *ReqBrand) String() string { return proto.CompactTextString(m) }
func (*ReqBrand) ProtoMessage()    {}
func (*ReqBrand) Descriptor() ([]byte, []int) {
	return fileDescriptor_4721fe843ce59954, []int{0}
}

func (m *ReqBrand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBrand.Unmarshal(m, b)
}
func (m *ReqBrand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBrand.Marshal(b, m, deterministic)
}
func (m *ReqBrand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBrand.Merge(m, src)
}
func (m *ReqBrand) XXX_Size() int {
	return xxx_messageInfo_ReqBrand.Size(m)
}
func (m *ReqBrand) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBrand.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBrand proto.InternalMessageInfo

func (m *ReqBrand) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqBrand) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *ReqBrand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqBrand) GetFirstChar() string {
	if m != nil {
		return m.FirstChar
	}
	return ""
}

type ReqIds struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIds) Reset()         { *m = ReqIds{} }
func (m *ReqIds) String() string { return proto.CompactTextString(m) }
func (*ReqIds) ProtoMessage()    {}
func (*ReqIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_4721fe843ce59954, []int{1}
}

func (m *ReqIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIds.Unmarshal(m, b)
}
func (m *ReqIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIds.Marshal(b, m, deterministic)
}
func (m *ReqIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIds.Merge(m, src)
}
func (m *ReqIds) XXX_Size() int {
	return xxx_messageInfo_ReqIds.Size(m)
}
func (m *ReqIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIds.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIds proto.InternalMessageInfo

func (m *ReqIds) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

//{total:100,rows:[{id:1,name:234,firstChar:N,firstName:2}]}
type RespBrand struct {
	Total                int64    `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*Rows  `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBrand) Reset()         { *m = RespBrand{} }
func (m *RespBrand) String() string { return proto.CompactTextString(m) }
func (*RespBrand) ProtoMessage()    {}
func (*RespBrand) Descriptor() ([]byte, []int) {
	return fileDescriptor_4721fe843ce59954, []int{2}
}

func (m *RespBrand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBrand.Unmarshal(m, b)
}
func (m *RespBrand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBrand.Marshal(b, m, deterministic)
}
func (m *RespBrand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBrand.Merge(m, src)
}
func (m *RespBrand) XXX_Size() int {
	return xxx_messageInfo_RespBrand.Size(m)
}
func (m *RespBrand) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBrand.DiscardUnknown(m)
}

var xxx_messageInfo_RespBrand proto.InternalMessageInfo

func (m *RespBrand) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespBrand) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Rows struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirstChar            string   `protobuf:"bytes,3,opt,name=firstChar,proto3" json:"firstChar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_4721fe843ce59954, []int{3}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rows) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rows) GetFirstChar() string {
	if m != nil {
		return m.FirstChar
	}
	return ""
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4721fe843ce59954, []int{4}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqBrand)(nil), "ReqBrand")
	proto.RegisterType((*ReqIds)(nil), "ReqIds")
	proto.RegisterType((*RespBrand)(nil), "RespBrand")
	proto.RegisterType((*Rows)(nil), "Rows")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/brand.proto", fileDescriptor_4721fe843ce59954) }

var fileDescriptor_4721fe843ce59954 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xbf, 0x6d, 0x46, 0x10, 0x19, 0x44, 0xd7, 0xe0, 0xa1, 0xee, 0x29, 0xa7, 0x14,
	0xaa, 0x47, 0x4f, 0x55, 0xc4, 0x5e, 0xb7, 0x9f, 0x60, 0xeb, 0x4e, 0xdb, 0x40, 0x9a, 0xa4, 0xbb,
	0xc1, 0xa2, 0x9f, 0x5e, 0x76, 0xd7, 0x46, 0x11, 0xbc, 0xbd, 0x79, 0x8f, 0x59, 0x7e, 0xf3, 0x16,
	0xae, 0x3b, 0xdd, 0xf6, 0xed, 0x4c, 0x6a, 0x92, 0x66, 0xb6, 0xd6, 0xb2, 0x51, 0xa5, 0x73, 0xb8,
	0x82, 0x89, 0xa0, 0xc3, 0xc2, 0x3a, 0x88, 0x10, 0x77, 0x72, 0x4b, 0x2c, 0x98, 0x06, 0x45, 0x22,
	0x9c, 0xb6, 0x9e, 0x6e, 0x8f, 0x86, 0x85, 0xde, 0xb3, 0xda, 0x7a, 0x8d, 0xdc, 0x13, 0x8b, 0xa6,
	0x41, 0x91, 0x09, 0xa7, 0xf1, 0x16, 0xb2, 0x4d, 0xa5, 0x4d, 0xff, 0xb4, 0x93, 0x9a, 0xc5, 0x2e,
	0xf8, 0x31, 0x78, 0x0e, 0xa9, 0xa0, 0xc3, 0x52, 0x19, 0xbc, 0x80, 0xa8, 0x52, 0x86, 0x05, 0xd3,
	0xa8, 0xc8, 0x84, 0x95, 0xfc, 0x11, 0x32, 0x41, 0xa6, 0xf3, 0x08, 0x97, 0x90, 0xf4, 0x6d, 0x2f,
	0x6b, 0xc7, 0x80, 0xc2, 0x0f, 0x78, 0x33, 0x40, 0x44, 0xc5, 0xd9, 0x3c, 0x29, 0x45, 0x7b, 0x34,
	0x9e, 0x85, 0xbf, 0x42, 0x6c, 0x27, 0x3c, 0x87, 0xb0, 0x52, 0xdf, 0x5b, 0x61, 0xa5, 0x06, 0xc6,
	0xf0, 0x3f, 0xc6, 0xe8, 0x2f, 0xe3, 0x03, 0xc4, 0x96, 0xc3, 0x6e, 0x6e, 0x6a, 0xb9, 0x75, 0x6f,
	0x4d, 0x84, 0xd3, 0xc8, 0x60, 0xbc, 0x27, 0x63, 0x6c, 0x39, 0xfe, 0xc1, 0xd3, 0x38, 0xff, 0x84,
	0xc4, 0x93, 0xdf, 0x41, 0xba, 0x22, 0xa9, 0xdf, 0x76, 0x98, 0x95, 0xa7, 0x46, 0x73, 0x28, 0x87,
	0xd3, 0xf8, 0x08, 0xaf, 0x20, 0x5e, 0xc9, 0x77, 0x42, 0x7f, 0x40, 0x9e, 0xb8, 0x90, 0x8f, 0x30,
	0x87, 0xc9, 0x4b, 0xd5, 0xa8, 0xc5, 0xc7, 0x52, 0xfd, 0xca, 0xec, 0x75, 0x36, 0x4b, 0x9f, 0xa9,
	0xa6, 0x9e, 0x70, 0x5c, 0xfa, 0x0a, 0x87, 0xbd, 0x75, 0xea, 0xbe, 0xf0, 0xfe, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0x1f, 0xbd, 0x1b, 0x4d, 0xdd, 0x01, 0x00, 0x00,
}
