// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/item.proto

package item

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchParams struct {
	Keywords string `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Brand    string `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	//spec
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	PageNo               int64    `protobuf:"zigzag64,5,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize             int64    `protobuf:"zigzag64,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort                 string   `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	SortField            string   `protobuf:"bytes,8,opt,name=sortField,proto3" json:"sortField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d217ee5fec361c0e, []int{0}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *SearchParams) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SearchParams) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *SearchParams) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *SearchParams) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *SearchParams) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchParams) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchParams) GetSortField() string {
	if m != nil {
		return m.SortField
	}
	return ""
}

type Model struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SellPoint            string   `protobuf:"bytes,3,opt,name=sell_point,json=sellPoint,proto3" json:"sell_point,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	StockCount           int64    `protobuf:"zigzag64,5,opt,name=stock_count,json=stockCount,proto3" json:"stock_count,omitempty"`
	Num                  int64    `protobuf:"zigzag64,6,opt,name=num,proto3" json:"num,omitempty"`
	Barcode              string   `protobuf:"bytes,7,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Image                string   `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	CategoryId           int64    `protobuf:"zigzag64,9,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           string   `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ItemSn               string   `protobuf:"bytes,13,opt,name=item_sn,json=itemSn,proto3" json:"item_sn,omitempty"`
	CostPirce            string   `protobuf:"bytes,14,opt,name=cost_pirce,json=costPirce,proto3" json:"cost_pirce,omitempty"`
	MarketPrice          string   `protobuf:"bytes,15,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	IsDefault            string   `protobuf:"bytes,16,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	GoodsId              int64    `protobuf:"zigzag64,17,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	SellerId             string   `protobuf:"bytes,18,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	CartThumbnail        string   `protobuf:"bytes,19,opt,name=cart_thumbnail,json=cartThumbnail,proto3" json:"cart_thumbnail,omitempty"`
	Category             string   `protobuf:"bytes,20,opt,name=category,proto3" json:"category,omitempty"`
	Brand                string   `protobuf:"bytes,21,opt,name=brand,proto3" json:"brand,omitempty"`
	Spec                 string   `protobuf:"bytes,22,opt,name=spec,proto3" json:"spec,omitempty"`
	Seller               string   `protobuf:"bytes,23,opt,name=seller,proto3" json:"seller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_d217ee5fec361c0e, []int{1}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Model) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Model) GetSellPoint() string {
	if m != nil {
		return m.SellPoint
	}
	return ""
}

func (m *Model) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Model) GetStockCount() int64 {
	if m != nil {
		return m.StockCount
	}
	return 0
}

func (m *Model) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Model) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *Model) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Model) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Model) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Model) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Model) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Model) GetItemSn() string {
	if m != nil {
		return m.ItemSn
	}
	return ""
}

func (m *Model) GetCostPirce() string {
	if m != nil {
		return m.CostPirce
	}
	return ""
}

func (m *Model) GetMarketPrice() string {
	if m != nil {
		return m.MarketPrice
	}
	return ""
}

func (m *Model) GetIsDefault() string {
	if m != nil {
		return m.IsDefault
	}
	return ""
}

func (m *Model) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *Model) GetSellerId() string {
	if m != nil {
		return m.SellerId
	}
	return ""
}

func (m *Model) GetCartThumbnail() string {
	if m != nil {
		return m.CartThumbnail
	}
	return ""
}

func (m *Model) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Model) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Model) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Model) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

type RespSearch struct {
	Rows                 []*Model `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	TotalPages           int64    `protobuf:"zigzag64,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSearch) Reset()         { *m = RespSearch{} }
func (m *RespSearch) String() string { return proto.CompactTextString(m) }
func (*RespSearch) ProtoMessage()    {}
func (*RespSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d217ee5fec361c0e, []int{2}
}

func (m *RespSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSearch.Unmarshal(m, b)
}
func (m *RespSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSearch.Marshal(b, m, deterministic)
}
func (m *RespSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSearch.Merge(m, src)
}
func (m *RespSearch) XXX_Size() int {
	return xxx_messageInfo_RespSearch.Size(m)
}
func (m *RespSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RespSearch proto.InternalMessageInfo

func (m *RespSearch) GetRows() []*Model {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *RespSearch) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchParams)(nil), "searchParams")
	proto.RegisterType((*Model)(nil), "Model")
	proto.RegisterType((*RespSearch)(nil), "respSearch")
}

func init() { proto.RegisterFile("proto/areas/item.proto", fileDescriptor_d217ee5fec361c0e) }

var fileDescriptor_d217ee5fec361c0e = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x86, 0x49, 0x9b, 0xe6, 0x63, 0xf2, 0x41, 0x31, 0x25, 0x35, 0x81, 0x42, 0x89, 0x04, 0xca,
	0x29, 0x95, 0xca, 0x4f, 0x00, 0x21, 0x72, 0x00, 0x45, 0x49, 0xef, 0x2b, 0xc7, 0x1e, 0x52, 0x2b,
	0xbb, 0xeb, 0x95, 0xed, 0x55, 0x55, 0x7e, 0x29, 0xbf, 0x84, 0x33, 0xf2, 0xd8, 0xf9, 0xe0, 0xd0,
	0x53, 0xfc, 0x3e, 0xe3, 0x8c, 0xfd, 0xce, 0xbe, 0x86, 0x51, 0x65, 0x8d, 0x37, 0x37, 0xc2, 0xa2,
	0x70, 0x37, 0xda, 0x63, 0x31, 0x23, 0x30, 0xf9, 0xd3, 0x80, 0xbe, 0x43, 0x61, 0xe5, 0xfd, 0x42,
	0x58, 0x51, 0x38, 0x36, 0x86, 0xce, 0x16, 0x1f, 0x1f, 0x8c, 0x55, 0x8e, 0x37, 0xae, 0x1b, 0xd3,
	0xee, 0x72, 0xaf, 0x43, 0x4d, 0x0a, 0x8f, 0x1b, 0x63, 0x1f, 0xf9, 0x49, 0xac, 0xed, 0x34, 0xbb,
	0x80, 0xb3, 0xb5, 0x15, 0xa5, 0xe2, 0xa7, 0x54, 0x88, 0x22, 0xd0, 0xca, 0x6a, 0x89, 0xbc, 0x19,
	0x29, 0x09, 0x36, 0x82, 0x56, 0x25, 0x36, 0xf8, 0xd3, 0xf0, 0xb3, 0xeb, 0xc6, 0x94, 0x2d, 0x93,
	0x0a, 0xfd, 0xc3, 0x6a, 0xa5, 0x7f, 0x23, 0x6f, 0x51, 0x65, 0xaf, 0x19, 0x83, 0xa6, 0x33, 0xd6,
	0xf3, 0x36, 0x35, 0xa2, 0x35, 0x7b, 0x0b, 0xdd, 0xf0, 0xfb, 0x4d, 0x63, 0xae, 0x78, 0x87, 0x0a,
	0x07, 0x30, 0xf9, 0xdb, 0x84, 0xb3, 0x1f, 0x46, 0x61, 0xce, 0x86, 0x70, 0xa2, 0x15, 0xb9, 0x61,
	0xcb, 0x13, 0x4d, 0xb7, 0xf2, 0xda, 0xe7, 0x98, 0x4c, 0x44, 0xc1, 0xae, 0x00, 0x1c, 0xe6, 0x79,
	0x56, 0x19, 0x5d, 0xfa, 0x64, 0xa3, 0x1b, 0xc8, 0x22, 0x80, 0x27, 0xac, 0xbc, 0x87, 0x9e, 0xf3,
	0x46, 0x6e, 0x33, 0x69, 0xea, 0xd2, 0x27, 0x3f, 0x40, 0xe8, 0x4b, 0x20, 0xec, 0x1c, 0x4e, 0xcb,
	0xba, 0x48, 0x76, 0xc2, 0x92, 0x71, 0x68, 0xaf, 0x85, 0x95, 0x46, 0x61, 0x32, 0xb3, 0x93, 0xe1,
	0x08, 0x5d, 0x88, 0x0d, 0x26, 0x2f, 0x51, 0xb0, 0x77, 0x00, 0xbb, 0x29, 0xcf, 0x15, 0xef, 0xc6,
	0x13, 0x0e, 0x24, 0x4c, 0xd3, 0x79, 0xe1, 0x6b, 0xc7, 0x81, 0xfe, 0x96, 0x54, 0xb8, 0x9a, 0xb4,
	0x28, 0x3c, 0x66, 0x5e, 0x17, 0xc8, 0x7b, 0x54, 0x84, 0x88, 0xee, 0x74, 0x41, 0x77, 0xaf, 0x2b,
	0xb5, 0xdf, 0xd0, 0x8f, 0x1b, 0x22, 0xa2, 0x0d, 0x97, 0xd0, 0x0e, 0x51, 0xc9, 0x5c, 0xc9, 0x07,
	0xb1, 0x75, 0x90, 0xab, 0x32, 0x8c, 0x4a, 0x1a, 0xe7, 0xb3, 0x4a, 0x5b, 0x89, 0x7c, 0x18, 0x47,
	0x15, 0xc8, 0x22, 0x00, 0xf6, 0x01, 0xfa, 0x85, 0xb0, 0x5b, 0xf4, 0x59, 0x9c, 0xd8, 0x73, 0xda,
	0xd0, 0x8b, 0x6c, 0x41, 0x73, 0xbb, 0x02, 0xd0, 0x2e, 0x53, 0xf8, 0x4b, 0xd4, 0xb9, 0xe7, 0xe7,
	0xb1, 0x83, 0x76, 0x5f, 0x23, 0x60, 0xaf, 0xa1, 0xb3, 0x31, 0x46, 0xb9, 0x4c, 0x2b, 0xfe, 0x82,
	0x1c, 0xb7, 0x49, 0xcf, 0x15, 0x7b, 0x03, 0xf4, 0x51, 0xd0, 0x86, 0x1a, 0x8b, 0x29, 0x8c, 0x60,
	0xae, 0xd8, 0x47, 0x18, 0x4a, 0x61, 0x7d, 0xe6, 0xef, 0xeb, 0x62, 0x5d, 0x0a, 0x9d, 0xf3, 0x97,
	0xb4, 0x63, 0x10, 0xe8, 0xdd, 0x0e, 0xfe, 0x17, 0xe4, 0x8b, 0xa7, 0x82, 0xfc, 0xea, 0x38, 0xc8,
	0x21, 0x7e, 0x15, 0x4a, 0x3e, 0x4a, 0xf1, 0xab, 0x50, 0xd2, 0xe0, 0xe9, 0x60, 0x7e, 0x99, 0x06,
	0x4f, 0x6a, 0xf2, 0x1d, 0xc0, 0xa2, 0xab, 0x56, 0xf4, 0xac, 0xd8, 0x18, 0x9a, 0xd6, 0x3c, 0x84,
	0xc7, 0x74, 0x3a, 0xed, 0xdd, 0xb6, 0x66, 0x14, 0xc9, 0x25, 0xb1, 0xf0, 0x69, 0xbd, 0xf1, 0x22,
	0x5f, 0x88, 0x0d, 0x3a, 0x4a, 0x23, 0x5b, 0x1e, 0x91, 0xdb, 0x19, 0x34, 0xe7, 0x1e, 0x0b, 0xf6,
	0x09, 0x5a, 0xa9, 0xdb, 0x60, 0x76, 0xfc, 0x5a, 0xc7, 0xbd, 0xd9, 0xe1, 0xa4, 0xc9, 0xb3, 0x75,
	0x8b, 0x1e, 0xf5, 0xe7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x84, 0xc4, 0xf7, 0xee, 0x03,
	0x00, 0x00,
}
