// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/areas/item.proto

/*
Package item is a generated protocol buffer package.

It is generated from these files:
	proto/areas/item.proto

It has these top-level messages:
	SearchParams
	Model
	RespSearch
*/
package item

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Item service

type ItemService interface {
	Search(ctx context.Context, in *SearchParams, opts ...client.CallOption) (*RespSearch, error)
}

type itemService struct {
	c    client.Client
	name string
}

func NewItemService(name string, c client.Client) ItemService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "item"
	}
	return &itemService{
		c:    c,
		name: name,
	}
}

func (c *itemService) Search(ctx context.Context, in *SearchParams, opts ...client.CallOption) (*RespSearch, error) {
	req := c.c.NewRequest(c.name, "Item.Search", in)
	out := new(RespSearch)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Item service

type ItemHandler interface {
	Search(context.Context, *SearchParams, *RespSearch) error
}

func RegisterItemHandler(s server.Server, hdlr ItemHandler, opts ...server.HandlerOption) error {
	type item interface {
		Search(ctx context.Context, in *SearchParams, out *RespSearch) error
	}
	type Item struct {
		item
	}
	h := &itemHandler{hdlr}
	return s.Handle(s.NewHandler(&Item{h}, opts...))
}

type itemHandler struct {
	ItemHandler
}

func (h *itemHandler) Search(ctx context.Context, in *SearchParams, out *RespSearch) error {
	return h.ItemHandler.Search(ctx, in, out)
}
