// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/areas/item.proto

/*
Package itemCat is a generated protocol buffer package.

It is generated from these files:
	proto/areas/item.proto

It has these top-level messages:
	ItemCatArr
	ItemCatModel
	Resp
*/
package itemCat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ItemCat service

type ItemCatService interface {
	FindByParentId(ctx context.Context, in *ItemCatModel, opts ...client.CallOption) (*ItemCatArr, error)
	FindAll(ctx context.Context, in *ItemCatModel, opts ...client.CallOption) (*ItemCatArr, error)
}

type itemCatService struct {
	c    client.Client
	name string
}

func NewItemCatService(name string, c client.Client) ItemCatService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "itemcat"
	}
	return &itemCatService{
		c:    c,
		name: name,
	}
}

func (c *itemCatService) FindByParentId(ctx context.Context, in *ItemCatModel, opts ...client.CallOption) (*ItemCatArr, error) {
	req := c.c.NewRequest(c.name, "ItemCat.FindByParentId", in)
	out := new(ItemCatArr)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemCatService) FindAll(ctx context.Context, in *ItemCatModel, opts ...client.CallOption) (*ItemCatArr, error) {
	req := c.c.NewRequest(c.name, "ItemCat.FindAll", in)
	out := new(ItemCatArr)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ItemCat service

type ItemCatHandler interface {
	FindByParentId(context.Context, *ItemCatModel, *ItemCatArr) error
	FindAll(context.Context, *ItemCatModel, *ItemCatArr) error
}

func RegisterItemCatHandler(s server.Server, hdlr ItemCatHandler, opts ...server.HandlerOption) error {
	type itemCat interface {
		FindByParentId(ctx context.Context, in *ItemCatModel, out *ItemCatArr) error
		FindAll(ctx context.Context, in *ItemCatModel, out *ItemCatArr) error
	}
	type ItemCat struct {
		itemCat
	}
	h := &itemCatHandler{hdlr}
	return s.Handle(s.NewHandler(&ItemCat{h}, opts...))
}

type itemCatHandler struct {
	ItemCatHandler
}

func (h *itemCatHandler) FindByParentId(ctx context.Context, in *ItemCatModel, out *ItemCatArr) error {
	return h.ItemCatHandler.FindByParentId(ctx, in, out)
}

func (h *itemCatHandler) FindAll(ctx context.Context, in *ItemCatModel, out *ItemCatArr) error {
	return h.ItemCatHandler.FindAll(ctx, in, out)
}
