// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/content.proto

package content

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ids struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e5b3f803a46ebe6, []int{0}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ReqContent struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqContent) Reset()         { *m = ReqContent{} }
func (m *ReqContent) String() string { return proto.CompactTextString(m) }
func (*ReqContent) ProtoMessage()    {}
func (*ReqContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e5b3f803a46ebe6, []int{1}
}

func (m *ReqContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqContent.Unmarshal(m, b)
}
func (m *ReqContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqContent.Marshal(b, m, deterministic)
}
func (m *ReqContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqContent.Merge(m, src)
}
func (m *ReqContent) XXX_Size() int {
	return xxx_messageInfo_ReqContent.Size(m)
}
func (m *ReqContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqContent.DiscardUnknown(m)
}

var xxx_messageInfo_ReqContent proto.InternalMessageInfo

func (m *ReqContent) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqContent) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type RespContent struct {
	Total                int64           `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*ContentModel `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RespContent) Reset()         { *m = RespContent{} }
func (m *RespContent) String() string { return proto.CompactTextString(m) }
func (*RespContent) ProtoMessage()    {}
func (*RespContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e5b3f803a46ebe6, []int{2}
}

func (m *RespContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespContent.Unmarshal(m, b)
}
func (m *RespContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespContent.Marshal(b, m, deterministic)
}
func (m *RespContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespContent.Merge(m, src)
}
func (m *RespContent) XXX_Size() int {
	return xxx_messageInfo_RespContent.Size(m)
}
func (m *RespContent) XXX_DiscardUnknown() {
	xxx_messageInfo_RespContent.DiscardUnknown(m)
}

var xxx_messageInfo_RespContent proto.InternalMessageInfo

func (m *RespContent) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespContent) GetRows() []*ContentModel {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ContentModel struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           int64    `protobuf:"zigzag64,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Pic                  string   `protobuf:"bytes,5,opt,name=pic,proto3" json:"pic,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	SortOrder            int64    `protobuf:"zigzag64,7,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentModel) Reset()         { *m = ContentModel{} }
func (m *ContentModel) String() string { return proto.CompactTextString(m) }
func (*ContentModel) ProtoMessage()    {}
func (*ContentModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e5b3f803a46ebe6, []int{3}
}

func (m *ContentModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentModel.Unmarshal(m, b)
}
func (m *ContentModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentModel.Marshal(b, m, deterministic)
}
func (m *ContentModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentModel.Merge(m, src)
}
func (m *ContentModel) XXX_Size() int {
	return xxx_messageInfo_ContentModel.Size(m)
}
func (m *ContentModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentModel.DiscardUnknown(m)
}

var xxx_messageInfo_ContentModel proto.InternalMessageInfo

func (m *ContentModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContentModel) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *ContentModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ContentModel) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ContentModel) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *ContentModel) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContentModel) GetSortOrder() int64 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e5b3f803a46ebe6, []int{4}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Ids)(nil), "Ids")
	proto.RegisterType((*ReqContent)(nil), "ReqContent")
	proto.RegisterType((*RespContent)(nil), "RespContent")
	proto.RegisterType((*ContentModel)(nil), "ContentModel")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/content.proto", fileDescriptor_8e5b3f803a46ebe6) }

var fileDescriptor_8e5b3f803a46ebe6 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x9b, 0xff, 0xf6, 0xb4, 0x8a, 0x1c, 0xc4, 0x8e, 0x45, 0x25, 0x06, 0x84, 0x78, 0x93,
	0x42, 0xed, 0x0b, 0x88, 0x52, 0xe8, 0x85, 0x14, 0x46, 0x7c, 0x80, 0x31, 0x73, 0xac, 0x81, 0x98,
	0x89, 0x33, 0x53, 0x64, 0x5f, 0x6a, 0xef, 0xf6, 0xfd, 0x96, 0x99, 0xa4, 0xdb, 0x76, 0x61, 0xef,
	0xbe, 0xef, 0x97, 0xf3, 0x67, 0xce, 0x47, 0xe0, 0x4d, 0xaf, 0x95, 0x55, 0x2b, 0xa1, 0x49, 0x98,
	0x55, 0xad, 0x3a, 0x4b, 0x9d, 0xad, 0x3c, 0x2b, 0x16, 0x10, 0xed, 0xa4, 0xc1, 0x97, 0x10, 0x35,
	0xd2, 0xb0, 0x20, 0x8f, 0xca, 0x29, 0x77, 0xb2, 0xd8, 0x00, 0x70, 0xfa, 0xf7, 0x75, 0x28, 0x46,
	0x84, 0xb8, 0x17, 0x07, 0x62, 0x41, 0x1e, 0x94, 0x09, 0xf7, 0xda, 0x31, 0xad, 0xfe, 0x1b, 0x16,
	0x0e, 0xcc, 0xe9, 0x62, 0x0b, 0x33, 0x4e, 0xa6, 0x3f, 0xb5, 0xbd, 0x82, 0xc4, 0x2a, 0x2b, 0x5a,
	0xdf, 0x87, 0x7c, 0x30, 0xf8, 0xe1, 0xa1, 0x31, 0x2a, 0x67, 0xeb, 0xe7, 0xd5, 0x58, 0xfd, 0x5d,
	0x49, 0x6a, 0xc7, 0x39, 0xb7, 0x01, 0xcc, 0x2f, 0x31, 0xbe, 0x80, 0xb0, 0x91, 0xe3, 0x98, 0xb0,
	0x91, 0xf8, 0x1e, 0xa0, 0x16, 0x96, 0x0e, 0x4a, 0xdf, 0xec, 0xa4, 0x7f, 0x02, 0xf2, 0x0b, 0xe2,
	0x37, 0x37, 0xb6, 0x25, 0x16, 0xe5, 0x41, 0x39, 0xe5, 0x83, 0x71, 0x67, 0x1e, 0x75, 0xcb, 0x62,
	0xcf, 0x9c, 0x74, 0xa4, 0x6f, 0x6a, 0x96, 0x0c, 0xa4, 0x6f, 0x6a, 0x7c, 0x0d, 0xa9, 0xb1, 0xc2,
	0x1e, 0x0d, 0x4b, 0x3d, 0x1c, 0x1d, 0xbe, 0x85, 0xa9, 0x51, 0xda, 0xee, 0xb5, 0x24, 0xcd, 0x32,
	0xbf, 0xf0, 0x0c, 0x8a, 0x0d, 0xc4, 0xee, 0x70, 0x17, 0xca, 0xef, 0x56, 0x1c, 0xfc, 0x4b, 0x9f,
	0x71, 0xaf, 0x91, 0x41, 0xf6, 0x97, 0x8c, 0x71, 0xf9, 0x85, 0x7e, 0xe4, 0xc9, 0xae, 0xef, 0x02,
	0xc8, 0x4e, 0x59, 0x7d, 0x84, 0xf4, 0x07, 0x09, 0x5d, 0xff, 0xc1, 0x59, 0x75, 0x4e, 0x7e, 0x39,
	0xaf, 0x2e, 0x02, 0x2d, 0x26, 0xf8, 0x0e, 0xa2, 0x2f, 0x52, 0xe2, 0x75, 0x6a, 0xcb, 0xc4, 0x57,
	0x15, 0x13, 0x5c, 0x40, 0xfa, 0x8d, 0x5a, 0xb2, 0x84, 0x71, 0xb5, 0x93, 0xe6, 0xfc, 0xe1, 0x13,
	0x64, 0xdb, 0xa6, 0x93, 0xfb, 0x8e, 0x1e, 0xf7, 0x5e, 0xdb, 0x62, 0x82, 0x39, 0xa4, 0x3f, 0x7b,
	0x29, 0x2c, 0x3d, 0xb5, 0xe5, 0x57, 0xea, 0x7f, 0x9e, 0xcf, 0xf7, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x56, 0x91, 0xcf, 0x59, 0x02, 0x00, 0x00,
}
