// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_292c9cdd33c5d334, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Info) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292c9cdd33c5d334, []int{1}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Resp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/login.proto", fileDescriptor_292c9cdd33c5d334) }

var fileDescriptor_292c9cdd33c5d334 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x6d, 0x4d, 0xb4, 0xde, 0x18, 0x84, 0x86, 0x4e, 0xa5, 0x93, 0x53, 0x0b, 0xba, 0xbb,
	0x0b, 0x4e, 0xfd, 0x07, 0x11, 0xaf, 0x45, 0x6c, 0x93, 0x92, 0xab, 0xf8, 0xf7, 0x25, 0x57, 0x22,
	0xe8, 0xf6, 0xbe, 0xf7, 0xc8, 0xcb, 0x3b, 0xc8, 0x27, 0xef, 0x66, 0xd7, 0x18, 0x8f, 0x86, 0x9a,
	0xc1, 0xf5, 0x0f, 0x5b, 0xb3, 0x53, 0x9d, 0x41, 0x5c, 0x6c, 0xe7, 0x54, 0x01, 0xd9, 0x8b, 0xd0,
	0x5b, 0x33, 0xa2, 0x4e, 0xca, 0xe4, 0xb0, 0x6b, 0xbf, 0x1c, 0xb2, 0xc9, 0x10, 0xbd, 0x9d, 0xbf,
	0xeb, 0x74, 0xc9, 0x22, 0x57, 0x1d, 0x88, 0x16, 0x69, 0x52, 0x0a, 0x44, 0x37, 0x98, 0x9e, 0xdf,
	0x66, 0x2d, 0xeb, 0x9f, 0xce, 0xf4, 0xaf, 0x73, 0x0f, 0x72, 0x76, 0x4f, 0xb4, 0x7a, 0xcd, 0xc1,
	0x02, 0x4a, 0xc3, 0x76, 0x44, 0x22, 0xd3, 0xa3, 0x16, 0xec, 0x47, 0x3c, 0x96, 0x20, 0xaf, 0x61,
	0xb6, 0xca, 0xa3, 0x90, 0x75, 0x18, 0x5e, 0xc8, 0x3a, 0xfc, 0x5f, 0xad, 0x6e, 0x1b, 0x3e, 0xe8,
	0xf4, 0x09, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0c, 0xa9, 0x5e, 0xeb, 0x00, 0x00, 0x00,
}
