// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/specification.proto

package specification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//--response
//response.rows;//结果
//respons
//--requeste.total;//更新总记录数
//
//seller/search.do?page=1&rows=10
//{status: "0"}
type ReqSearch struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSearch) Reset()         { *m = ReqSearch{} }
func (m *ReqSearch) String() string { return proto.CompactTextString(m) }
func (*ReqSearch) ProtoMessage()    {}
func (*ReqSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{0}
}

func (m *ReqSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSearch.Unmarshal(m, b)
}
func (m *ReqSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSearch.Marshal(b, m, deterministic)
}
func (m *ReqSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSearch.Merge(m, src)
}
func (m *ReqSearch) XXX_Size() int {
	return xxx_messageInfo_ReqSearch.Size(m)
}
func (m *ReqSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSearch proto.InternalMessageInfo

func (m *ReqSearch) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqSearch) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type ReqIds struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIds) Reset()         { *m = ReqIds{} }
func (m *ReqIds) String() string { return proto.CompactTextString(m) }
func (*ReqIds) ProtoMessage()    {}
func (*ReqIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{1}
}

func (m *ReqIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIds.Unmarshal(m, b)
}
func (m *ReqIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIds.Marshal(b, m, deterministic)
}
func (m *ReqIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIds.Merge(m, src)
}
func (m *ReqIds) XXX_Size() int {
	return xxx_messageInfo_ReqIds.Size(m)
}
func (m *ReqIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIds.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIds proto.InternalMessageInfo

func (m *ReqIds) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

//{total:100,rows:[{id:1,name:234,firstChar:N,firstName:2}]}
type RespSearch struct {
	Total                int64    `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*Rows  `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSearch) Reset()         { *m = RespSearch{} }
func (m *RespSearch) String() string { return proto.CompactTextString(m) }
func (*RespSearch) ProtoMessage()    {}
func (*RespSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{2}
}

func (m *RespSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSearch.Unmarshal(m, b)
}
func (m *RespSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSearch.Marshal(b, m, deterministic)
}
func (m *RespSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSearch.Merge(m, src)
}
func (m *RespSearch) XXX_Size() int {
	return xxx_messageInfo_RespSearch.Size(m)
}
func (m *RespSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RespSearch proto.InternalMessageInfo

func (m *RespSearch) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespSearch) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

//{"specificationOptionList":[{"optionName":"2","orders":"2"},{"optionName":"2","orders":"2"}],"specification":{"specName":"2"}}
type ReqAdd struct {
	Specification           *Rows                         `protobuf:"bytes,1,opt,name=specification,proto3" json:"specification,omitempty"`
	SpecificationOptionList []*ReqAdd_SpecificationOption `protobuf:"bytes,2,rep,name=specificationOptionList,proto3" json:"specificationOptionList,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                      `json:"-"`
	XXX_unrecognized        []byte                        `json:"-"`
	XXX_sizecache           int32                         `json:"-"`
}

func (m *ReqAdd) Reset()         { *m = ReqAdd{} }
func (m *ReqAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAdd) ProtoMessage()    {}
func (*ReqAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{3}
}

func (m *ReqAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAdd.Unmarshal(m, b)
}
func (m *ReqAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAdd.Marshal(b, m, deterministic)
}
func (m *ReqAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAdd.Merge(m, src)
}
func (m *ReqAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAdd.Size(m)
}
func (m *ReqAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAdd proto.InternalMessageInfo

func (m *ReqAdd) GetSpecification() *Rows {
	if m != nil {
		return m.Specification
	}
	return nil
}

func (m *ReqAdd) GetSpecificationOptionList() []*ReqAdd_SpecificationOption {
	if m != nil {
		return m.SpecificationOptionList
	}
	return nil
}

type ReqAdd_SpecificationOption struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	OptionName           string   `protobuf:"bytes,2,opt,name=optionName,proto3" json:"optionName,omitempty"`
	SpecId               int64    `protobuf:"zigzag64,3,opt,name=specId,proto3" json:"specId,omitempty"`
	Orders               string   `protobuf:"bytes,4,opt,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAdd_SpecificationOption) Reset()         { *m = ReqAdd_SpecificationOption{} }
func (m *ReqAdd_SpecificationOption) String() string { return proto.CompactTextString(m) }
func (*ReqAdd_SpecificationOption) ProtoMessage()    {}
func (*ReqAdd_SpecificationOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{3, 0}
}

func (m *ReqAdd_SpecificationOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAdd_SpecificationOption.Unmarshal(m, b)
}
func (m *ReqAdd_SpecificationOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAdd_SpecificationOption.Marshal(b, m, deterministic)
}
func (m *ReqAdd_SpecificationOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAdd_SpecificationOption.Merge(m, src)
}
func (m *ReqAdd_SpecificationOption) XXX_Size() int {
	return xxx_messageInfo_ReqAdd_SpecificationOption.Size(m)
}
func (m *ReqAdd_SpecificationOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAdd_SpecificationOption.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAdd_SpecificationOption proto.InternalMessageInfo

func (m *ReqAdd_SpecificationOption) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReqAdd_SpecificationOption) GetOptionName() string {
	if m != nil {
		return m.OptionName
	}
	return ""
}

func (m *ReqAdd_SpecificationOption) GetSpecId() int64 {
	if m != nil {
		return m.SpecId
	}
	return 0
}

func (m *ReqAdd_SpecificationOption) GetOrders() string {
	if m != nil {
		return m.Orders
	}
	return ""
}

type Rows struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	SpecName             string   `protobuf:"bytes,2,opt,name=specName,proto3" json:"specName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{4}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rows) GetSpecName() string {
	if m != nil {
		return m.SpecName
	}
	return ""
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a4cb80d41cd1fa, []int{5}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSearch)(nil), "ReqSearch")
	proto.RegisterType((*ReqIds)(nil), "ReqIds")
	proto.RegisterType((*RespSearch)(nil), "RespSearch")
	proto.RegisterType((*ReqAdd)(nil), "ReqAdd")
	proto.RegisterType((*ReqAdd_SpecificationOption)(nil), "ReqAdd.SpecificationOption")
	proto.RegisterType((*Rows)(nil), "Rows")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/specification.proto", fileDescriptor_78a4cb80d41cd1fa) }

var fileDescriptor_78a4cb80d41cd1fa = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6a, 0xea, 0x40,
	0x10, 0x36, 0xbf, 0xea, 0x88, 0x87, 0xc3, 0x9c, 0xc3, 0x31, 0x27, 0x42, 0x2b, 0xe9, 0x8d, 0x50,
	0x88, 0xa0, 0xbd, 0xed, 0x45, 0xa1, 0x14, 0x84, 0x52, 0x61, 0xc5, 0x07, 0xd8, 0xba, 0xab, 0x5d,
	0x50, 0x37, 0x66, 0x53, 0x7c, 0x80, 0xbe, 0x49, 0x9f, 0xb4, 0xec, 0x66, 0x8d, 0x06, 0xdb, 0x9b,
	0x30, 0x33, 0xdf, 0x7c, 0xdf, 0x64, 0xe6, 0x5b, 0xb8, 0xce, 0x72, 0x59, 0xc8, 0x11, 0xcd, 0x39,
	0x55, 0x23, 0x95, 0xf1, 0xa5, 0x58, 0x89, 0x25, 0x2d, 0x84, 0xdc, 0xa5, 0x06, 0x49, 0x26, 0xd0,
	0x26, 0x7c, 0x3f, 0xe7, 0x34, 0x5f, 0xbe, 0x21, 0x82, 0x9f, 0xd1, 0x35, 0x8f, 0x9c, 0x81, 0x33,
	0x0c, 0x88, 0x89, 0x75, 0x2d, 0x97, 0x07, 0x15, 0xb9, 0x65, 0x4d, 0xc7, 0x49, 0x0c, 0x21, 0xe1,
	0xfb, 0x29, 0x53, 0xf8, 0x1b, 0x3c, 0xc1, 0x54, 0xe4, 0x0c, 0xbc, 0x61, 0x9b, 0xe8, 0x30, 0xb9,
	0x07, 0x20, 0x5c, 0x65, 0x56, 0xf1, 0x2f, 0x04, 0x85, 0x2c, 0xe8, 0xc6, 0x48, 0x22, 0x29, 0x13,
	0xfc, 0x5f, 0x69, 0x7a, 0xc3, 0xce, 0x38, 0x48, 0x89, 0x3c, 0x28, 0x2b, 0xfd, 0xe1, 0x1a, 0xed,
	0x07, 0xc6, 0xf0, 0x16, 0xba, 0xb5, 0x3f, 0x36, 0x1a, 0x55, 0x7b, 0x1d, 0xc3, 0x05, 0xf4, 0x6a,
	0x85, 0x59, 0xa6, 0xbf, 0xcf, 0x42, 0x15, 0x76, 0x4a, 0x3f, 0x2d, 0x65, 0xd3, 0xf9, 0x65, 0x1b,
	0xf9, 0x89, 0x1b, 0xbf, 0xc3, 0x9f, 0x6f, 0xfa, 0xf1, 0x17, 0xb8, 0x82, 0xd9, 0x9d, 0x5c, 0xc1,
	0xf0, 0x0a, 0x40, 0x1a, 0xe4, 0x85, 0x6e, 0xb9, 0x39, 0x55, 0x9b, 0x9c, 0x55, 0xf0, 0x1f, 0x84,
	0x7a, 0xc2, 0x94, 0x45, 0x9e, 0xe1, 0xd8, 0x4c, 0xd7, 0x65, 0xce, 0x78, 0xae, 0x22, 0xdf, 0x70,
	0x6c, 0x96, 0x8c, 0xc1, 0xd7, 0x4b, 0x5e, 0xcc, 0x89, 0xa1, 0xa5, 0x99, 0x67, 0x53, 0xaa, 0x3c,
	0xb9, 0x03, 0x5f, 0x1f, 0x5e, 0x1b, 0xb6, 0xda, 0xd0, 0xb5, 0x61, 0xb5, 0x88, 0x89, 0x31, 0x82,
	0xe6, 0x96, 0x2b, 0xa5, 0xbd, 0x2d, 0x69, 0xc7, 0x74, 0xfc, 0xe9, 0x40, 0xb7, 0xb6, 0x21, 0xde,
	0x40, 0x68, 0xcd, 0x83, 0xb4, 0x7a, 0x1a, 0x71, 0x27, 0x3d, 0xb9, 0x9a, 0x34, 0xb0, 0x07, 0x9e,
	0xb6, 0xa8, 0x69, 0x8f, 0x1a, 0x07, 0x06, 0x4e, 0x1a, 0x18, 0x43, 0xf8, 0xc8, 0x37, 0xbc, 0xe0,
	0x25, 0x36, 0x65, 0xea, 0x84, 0xf5, 0xa1, 0xf9, 0x24, 0x76, 0x6c, 0xb6, 0xe3, 0x58, 0x9a, 0x18,
	0x1f, 0xf9, 0x25, 0x71, 0x91, 0x31, 0x7a, 0x24, 0x9e, 0x8b, 0xbe, 0x86, 0xe6, 0xad, 0x4e, 0xbe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x25, 0x92, 0x5c, 0xce, 0x02, 0x00, 0x00,
}
