// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/goods.proto

package goods

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ids struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c184e2bfec06758, []int{0}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Ids) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReqSearch struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSearch) Reset()         { *m = ReqSearch{} }
func (m *ReqSearch) String() string { return proto.CompactTextString(m) }
func (*ReqSearch) ProtoMessage()    {}
func (*ReqSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c184e2bfec06758, []int{1}
}

func (m *ReqSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSearch.Unmarshal(m, b)
}
func (m *ReqSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSearch.Marshal(b, m, deterministic)
}
func (m *ReqSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSearch.Merge(m, src)
}
func (m *ReqSearch) XXX_Size() int {
	return xxx_messageInfo_ReqSearch.Size(m)
}
func (m *ReqSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSearch proto.InternalMessageInfo

func (m *ReqSearch) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqSearch) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type RespSearch struct {
	Total                int64         `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*GoodsModel `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RespSearch) Reset()         { *m = RespSearch{} }
func (m *RespSearch) String() string { return proto.CompactTextString(m) }
func (*RespSearch) ProtoMessage()    {}
func (*RespSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c184e2bfec06758, []int{2}
}

func (m *RespSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSearch.Unmarshal(m, b)
}
func (m *RespSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSearch.Marshal(b, m, deterministic)
}
func (m *RespSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSearch.Merge(m, src)
}
func (m *RespSearch) XXX_Size() int {
	return xxx_messageInfo_RespSearch.Size(m)
}
func (m *RespSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RespSearch proto.InternalMessageInfo

func (m *RespSearch) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespSearch) GetRows() []*GoodsModel {
	if m != nil {
		return m.Rows
	}
	return nil
}

type GoodsModel struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId             string   `protobuf:"bytes,2,opt,name=sellerId,proto3" json:"sellerId,omitempty"`
	GoodsName            string   `protobuf:"bytes,3,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	DefaultItemId        int64    `protobuf:"zigzag64,4,opt,name=defaultItemId,proto3" json:"defaultItemId,omitempty"`
	AuditStatus          string   `protobuf:"bytes,5,opt,name=auditStatus,proto3" json:"auditStatus,omitempty"`
	IsMarketable         string   `protobuf:"bytes,6,opt,name=isMarketable,proto3" json:"isMarketable,omitempty"`
	BrandId              int64    `protobuf:"zigzag64,7,opt,name=brandId,proto3" json:"brandId,omitempty"`
	Caption              string   `protobuf:"bytes,8,opt,name=caption,proto3" json:"caption,omitempty"`
	Category1Id          int64    `protobuf:"zigzag64,9,opt,name=category1Id,proto3" json:"category1Id,omitempty"`
	Category2Id          int64    `protobuf:"zigzag64,10,opt,name=category2Id,proto3" json:"category2Id,omitempty"`
	Category3Id          int64    `protobuf:"zigzag64,11,opt,name=category3Id,proto3" json:"category3Id,omitempty"`
	SmallPic             string   `protobuf:"bytes,12,opt,name=smallPic,proto3" json:"smallPic,omitempty"`
	Price                float64  `protobuf:"fixed64,13,opt,name=price,proto3" json:"price,omitempty"`
	TypeTemplateId       int64    `protobuf:"zigzag64,14,opt,name=typeTemplateId,proto3" json:"typeTemplateId,omitempty"`
	IsEnableSpec         string   `protobuf:"bytes,15,opt,name=isEnableSpec,proto3" json:"isEnableSpec,omitempty"`
	IsDelete             string   `protobuf:"bytes,16,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsModel) Reset()         { *m = GoodsModel{} }
func (m *GoodsModel) String() string { return proto.CompactTextString(m) }
func (*GoodsModel) ProtoMessage()    {}
func (*GoodsModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c184e2bfec06758, []int{3}
}

func (m *GoodsModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsModel.Unmarshal(m, b)
}
func (m *GoodsModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsModel.Marshal(b, m, deterministic)
}
func (m *GoodsModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsModel.Merge(m, src)
}
func (m *GoodsModel) XXX_Size() int {
	return xxx_messageInfo_GoodsModel.Size(m)
}
func (m *GoodsModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsModel.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsModel proto.InternalMessageInfo

func (m *GoodsModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GoodsModel) GetSellerId() string {
	if m != nil {
		return m.SellerId
	}
	return ""
}

func (m *GoodsModel) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *GoodsModel) GetDefaultItemId() int64 {
	if m != nil {
		return m.DefaultItemId
	}
	return 0
}

func (m *GoodsModel) GetAuditStatus() string {
	if m != nil {
		return m.AuditStatus
	}
	return ""
}

func (m *GoodsModel) GetIsMarketable() string {
	if m != nil {
		return m.IsMarketable
	}
	return ""
}

func (m *GoodsModel) GetBrandId() int64 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *GoodsModel) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *GoodsModel) GetCategory1Id() int64 {
	if m != nil {
		return m.Category1Id
	}
	return 0
}

func (m *GoodsModel) GetCategory2Id() int64 {
	if m != nil {
		return m.Category2Id
	}
	return 0
}

func (m *GoodsModel) GetCategory3Id() int64 {
	if m != nil {
		return m.Category3Id
	}
	return 0
}

func (m *GoodsModel) GetSmallPic() string {
	if m != nil {
		return m.SmallPic
	}
	return ""
}

func (m *GoodsModel) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GoodsModel) GetTypeTemplateId() int64 {
	if m != nil {
		return m.TypeTemplateId
	}
	return 0
}

func (m *GoodsModel) GetIsEnableSpec() string {
	if m != nil {
		return m.IsEnableSpec
	}
	return ""
}

func (m *GoodsModel) GetIsDelete() string {
	if m != nil {
		return m.IsDelete
	}
	return ""
}

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c184e2bfec06758, []int{4}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Ids)(nil), "Ids")
	proto.RegisterType((*ReqSearch)(nil), "ReqSearch")
	proto.RegisterType((*RespSearch)(nil), "RespSearch")
	proto.RegisterType((*GoodsModel)(nil), "GoodsModel")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/goods.proto", fileDescriptor_9c184e2bfec06758) }

var fileDescriptor_9c184e2bfec06758 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x53, 0x5d, 0x8f, 0x93, 0x40,
	0x14, 0x5d, 0x96, 0xd2, 0x2d, 0x97, 0x6e, 0xdd, 0x4c, 0x8c, 0x3b, 0x69, 0x34, 0x12, 0x34, 0x86,
	0x27, 0x1a, 0x5b, 0xff, 0x81, 0x1a, 0x33, 0x0f, 0x6b, 0x0c, 0xd5, 0x1f, 0x30, 0xe5, 0xde, 0xad,
	0xc4, 0xa1, 0x20, 0x33, 0x8d, 0xd9, 0x3f, 0xee, 0xb3, 0x99, 0x01, 0xda, 0xe2, 0xdb, 0x3d, 0xe7,
	0x7e, 0x31, 0xe7, 0x1e, 0xe0, 0xbe, 0x69, 0x6b, 0x53, 0xaf, 0x64, 0x4b, 0x52, 0xaf, 0xf6, 0x75,
	0x8d, 0x3a, 0x73, 0x4c, 0xb2, 0x02, 0x5f, 0xa0, 0x66, 0x77, 0xe0, 0x97, 0xa8, 0xb9, 0x17, 0xfb,
	0x69, 0x98, 0xdb, 0x90, 0xbd, 0x80, 0xa9, 0x36, 0xd2, 0x1c, 0x35, 0xbf, 0x8e, 0xbd, 0x34, 0xcc,
	0x7b, 0x94, 0x6c, 0x20, 0xcc, 0xe9, 0xf7, 0x96, 0x64, 0x5b, 0xfc, 0x64, 0x0c, 0x26, 0x8d, 0xdc,
	0x13, 0xf7, 0x62, 0x2f, 0x0d, 0x72, 0x17, 0x5b, 0xae, 0xad, 0xff, 0x74, 0x6d, 0x41, 0xee, 0xe2,
	0xe4, 0x23, 0x40, 0x4e, 0xba, 0xe9, 0xbb, 0x9e, 0x43, 0x60, 0x6a, 0x23, 0x95, 0x6b, 0x63, 0x79,
	0x07, 0xd8, 0xeb, 0x53, 0x9f, 0x9f, 0x46, 0xeb, 0x28, 0xfb, 0x62, 0xbf, 0xf2, 0xa1, 0x46, 0x52,
	0xfd, 0x90, 0xbf, 0x3e, 0xc0, 0x99, 0x64, 0x0b, 0xb8, 0x2e, 0xb1, 0x1f, 0x71, 0x5d, 0x22, 0x5b,
	0xc2, 0x4c, 0x93, 0x52, 0xd4, 0x0a, 0xec, 0x3f, 0xf9, 0x84, 0xd9, 0x4b, 0x08, 0xdd, 0xa3, 0xbf,
	0xca, 0x8a, 0xb8, 0xef, 0x92, 0x67, 0x82, 0xbd, 0x85, 0x5b, 0xa4, 0x47, 0x79, 0x54, 0x46, 0x18,
	0xaa, 0x04, 0xf2, 0x89, 0x1b, 0x3a, 0x26, 0x59, 0x0c, 0x91, 0x3c, 0x62, 0x69, 0xb6, 0x9d, 0x2a,
	0x81, 0x9b, 0x72, 0x49, 0xb1, 0x04, 0xe6, 0xa5, 0x7e, 0x90, 0xed, 0x2f, 0x32, 0x72, 0xa7, 0x88,
	0x4f, 0x5d, 0xc9, 0x88, 0x63, 0x1c, 0x6e, 0x76, 0xad, 0x3c, 0xa0, 0x40, 0x7e, 0xe3, 0xb6, 0x0c,
	0xd0, 0x66, 0x0a, 0xd9, 0x98, 0xb2, 0x3e, 0xf0, 0x99, 0x6b, 0x1c, 0xa0, 0xdd, 0x5c, 0x48, 0x43,
	0xfb, 0xba, 0x7d, 0x7a, 0x2f, 0x90, 0x87, 0xae, 0xef, 0x92, 0xba, 0xac, 0x58, 0x0b, 0xe4, 0x30,
	0xae, 0x58, 0x8f, 0x2b, 0x36, 0x02, 0x79, 0x34, 0xae, 0xd8, 0x88, 0x4e, 0xbf, 0x4a, 0x2a, 0xf5,
	0xad, 0x2c, 0xf8, 0xbc, 0xd7, 0xaf, 0xc7, 0xf6, 0x62, 0x4d, 0x5b, 0x16, 0xc4, 0x6f, 0x63, 0x2f,
	0xf5, 0xf2, 0x0e, 0xb0, 0x77, 0xb0, 0x30, 0x4f, 0x0d, 0x7d, 0xa7, 0xaa, 0x51, 0xd2, 0x90, 0x40,
	0xbe, 0x70, 0x63, 0xff, 0x63, 0x3b, 0x5d, 0x3e, 0x1f, 0xec, 0xfb, 0xb7, 0x0d, 0x15, 0xfc, 0xd9,
	0xa0, 0xcb, 0x99, 0xb3, 0xdb, 0x4b, 0xfd, 0x89, 0x14, 0x19, 0xe2, 0x77, 0xdd, 0xf6, 0x01, 0x27,
	0x1f, 0x60, 0x62, 0xdd, 0x63, 0x9d, 0xf5, 0xa8, 0xe4, 0xde, 0xdd, 0x7c, 0x96, 0xbb, 0xd8, 0xaa,
	0x56, 0x91, 0xd6, 0xd6, 0x84, 0xdd, 0xd1, 0x07, 0xb8, 0x46, 0x08, 0x9c, 0x5b, 0xd8, 0x1b, 0x98,
	0xf6, 0xc6, 0x83, 0xec, 0x64, 0xdd, 0x65, 0x94, 0x9d, 0x1d, 0x99, 0x5c, 0xb1, 0x7b, 0x98, 0x76,
	0xdb, 0xd8, 0x24, 0x13, 0xa8, 0x97, 0x81, 0x4b, 0x27, 0x57, 0xec, 0x15, 0xcc, 0x7f, 0x34, 0x28,
	0x0d, 0xf5, 0x47, 0x1e, 0xa7, 0x77, 0x53, 0xf7, 0x1b, 0x6d, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xa6, 0xf7, 0x17, 0xe3, 0x61, 0x03, 0x00, 0x00,
}
