// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/areas/contentCategory.proto

package contentCategory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ids struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{0}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ReqContentCategory struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqContentCategory) Reset()         { *m = ReqContentCategory{} }
func (m *ReqContentCategory) String() string { return proto.CompactTextString(m) }
func (*ReqContentCategory) ProtoMessage()    {}
func (*ReqContentCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{1}
}

func (m *ReqContentCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqContentCategory.Unmarshal(m, b)
}
func (m *ReqContentCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqContentCategory.Marshal(b, m, deterministic)
}
func (m *ReqContentCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqContentCategory.Merge(m, src)
}
func (m *ReqContentCategory) XXX_Size() int {
	return xxx_messageInfo_ReqContentCategory.Size(m)
}
func (m *ReqContentCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqContentCategory.DiscardUnknown(m)
}

var xxx_messageInfo_ReqContentCategory proto.InternalMessageInfo

func (m *ReqContentCategory) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqContentCategory) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type RespContentCategory struct {
	Total                int64                   `protobuf:"zigzag64,1,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*ContentCategoryModel `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RespContentCategory) Reset()         { *m = RespContentCategory{} }
func (m *RespContentCategory) String() string { return proto.CompactTextString(m) }
func (*RespContentCategory) ProtoMessage()    {}
func (*RespContentCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{2}
}

func (m *RespContentCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespContentCategory.Unmarshal(m, b)
}
func (m *RespContentCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespContentCategory.Marshal(b, m, deterministic)
}
func (m *RespContentCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespContentCategory.Merge(m, src)
}
func (m *RespContentCategory) XXX_Size() int {
	return xxx_messageInfo_RespContentCategory.Size(m)
}
func (m *RespContentCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_RespContentCategory.DiscardUnknown(m)
}

var xxx_messageInfo_RespContentCategory proto.InternalMessageInfo

func (m *RespContentCategory) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RespContentCategory) GetRows() []*ContentCategoryModel {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ContentCategoryModel struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentCategoryModel) Reset()         { *m = ContentCategoryModel{} }
func (m *ContentCategoryModel) String() string { return proto.CompactTextString(m) }
func (*ContentCategoryModel) ProtoMessage()    {}
func (*ContentCategoryModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{3}
}

func (m *ContentCategoryModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentCategoryModel.Unmarshal(m, b)
}
func (m *ContentCategoryModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentCategoryModel.Marshal(b, m, deterministic)
}
func (m *ContentCategoryModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentCategoryModel.Merge(m, src)
}
func (m *ContentCategoryModel) XXX_Size() int {
	return xxx_messageInfo_ContentCategoryModel.Size(m)
}
func (m *ContentCategoryModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentCategoryModel.DiscardUnknown(m)
}

var xxx_messageInfo_ContentCategoryModel proto.InternalMessageInfo

func (m *ContentCategoryModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContentCategoryModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

type Resp struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f5ceae665add40, []int{5}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Resp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Ids)(nil), "Ids")
	proto.RegisterType((*ReqContentCategory)(nil), "ReqContentCategory")
	proto.RegisterType((*RespContentCategory)(nil), "RespContentCategory")
	proto.RegisterType((*ContentCategoryModel)(nil), "ContentCategoryModel")
	proto.RegisterType((*Req)(nil), "Req")
	proto.RegisterType((*Resp)(nil), "Resp")
}

func init() { proto.RegisterFile("proto/areas/contentCategory.proto", fileDescriptor_05f5ceae665add40) }

var fileDescriptor_05f5ceae665add40 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x26, 0x69, 0xed, 0x08, 0x2a, 0xd3, 0x4a, 0x43, 0x4f, 0x75, 0x41, 0xac, 0x97,
	0x14, 0xaa, 0x1e, 0x14, 0x2f, 0xa5, 0x22, 0xf4, 0x20, 0xc2, 0x0a, 0xde, 0xd7, 0xee, 0x58, 0x03,
	0xdb, 0x6c, 0x9b, 0x5d, 0x10, 0xff, 0xb3, 0x3f, 0x42, 0x76, 0x53, 0x15, 0x63, 0x7a, 0x7b, 0x33,
	0xb3, 0xdf, 0xe3, 0xcd, 0xb0, 0x70, 0xb2, 0x2e, 0xb4, 0xd5, 0x63, 0x51, 0x90, 0x30, 0xe3, 0x85,
	0xce, 0x2d, 0xe5, 0x76, 0x26, 0x2c, 0x2d, 0x75, 0xf1, 0x91, 0xfa, 0x19, 0xeb, 0x43, 0x38, 0x97,
	0x06, 0x8f, 0x20, 0xcc, 0xa4, 0x49, 0x82, 0x61, 0x38, 0xea, 0x70, 0x27, 0xd9, 0x2d, 0x20, 0xa7,
	0xcd, 0xec, 0x2f, 0x84, 0x08, 0xd1, 0x5a, 0x2c, 0x29, 0x09, 0x86, 0xc1, 0x28, 0xe6, 0x5e, 0xbb,
	0x5e, 0xa1, 0xdf, 0x4d, 0xd2, 0x2c, 0x7b, 0x4e, 0xb3, 0x67, 0xe8, 0x72, 0x32, 0xeb, 0x2a, 0xde,
	0x83, 0xd8, 0x6a, 0x2b, 0x94, 0xe7, 0x91, 0x97, 0x05, 0x9e, 0xff, 0x18, 0x84, 0xa3, 0xfd, 0xc9,
	0x71, 0x5a, 0xa1, 0x1e, 0xb4, 0x24, 0xb5, 0xf5, 0xbd, 0x81, 0x5e, 0xdd, 0x14, 0x0f, 0xa0, 0x99,
	0xc9, 0xad, 0x6b, 0x33, 0x93, 0x2e, 0x53, 0x2e, 0x56, 0xe4, 0x33, 0x75, 0xb8, 0xd7, 0x2c, 0x86,
	0x90, 0xd3, 0x86, 0x5d, 0x42, 0xe4, 0xa2, 0xb9, 0x27, 0xaf, 0x4a, 0x2c, 0x3d, 0xb4, 0xc7, 0xbd,
	0xc6, 0x04, 0xda, 0x2b, 0x32, 0xc6, 0x6d, 0x58, 0x92, 0xdf, 0xe5, 0xe4, 0x33, 0x80, 0xc3, 0xea,
	0x36, 0x57, 0xd0, 0x7a, 0x22, 0x51, 0x2c, 0xde, 0xb0, 0x9b, 0xfe, 0xbf, 0xd5, 0xa0, 0x97, 0xd6,
	0x9c, 0x80, 0x35, 0xf0, 0x14, 0xc2, 0xa9, 0x94, 0x58, 0xbf, 0xe7, 0x20, 0xf6, 0x14, 0x6b, 0x60,
	0x1f, 0x5a, 0x77, 0xa4, 0xc8, 0x12, 0x46, 0xe9, 0x5c, 0x9a, 0xdf, 0xc1, 0x35, 0xb4, 0xef, 0xb3,
	0x5c, 0x3e, 0xe6, 0xb4, 0xcb, 0xa3, 0xbe, 0xcd, 0x1a, 0x78, 0x56, 0xa2, 0x53, 0xa5, 0x30, 0x72,
	0x91, 0x77, 0x65, 0x7c, 0x69, 0xf9, 0xdf, 0x71, 0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xb6,
	0x22, 0x03, 0x42, 0x02, 0x00, 0x00,
}
